### PR TITLE
Add Ember Times to list

### PR DESCRIPTION
**Pull request by amyrlam**
* Added Ember Times cc @jessica-jordan
* Changed EmberJS Weekly to Ember Weekly cc @ebryn @rtablada

### CODE REVIEW

**Comment by zudochkin** [comment]
@amyrlam thanks for your contribution, unfortunately, I could not find a form for email subscription, can you please help me with that?

**Comment by ferhatelmas** [comment]
@zudochkin it's very unfortunate for the design, you should see it if scroll to the bottom of the page.

**Comment by ferhatelmas** [comment]
sorry to be more specific, I was talking about ember weekly.

Regarding Ember times, correct url should be https://the-emberjs-times.ongoodbits.com/

**Comment by zudochkin** [comment]
@ferhatelmas, thanks, Ferhat, for an explanation. @amyrlam, could you please make a small fix for that?

**Comment by amyrlam** [comment]
@zudochkin @ferhatelmas ah sorry, just squashed the change in

**Comment by zudochkin** [comment]
@amyrlam thanks for your awesome contribution. 👍 ❤️

**Pull request merged**
