### PR TITLE
Added seniormindset.com to Awesome news

### PR DESCRIPTION
**Pull request by Chris2Brooks**

### CODE REVIEW

**Comment by ferhatelmas** [comment]
@Chris2Brooks considering if it's just marketing or not, is there an archive or a sample ?

**Comment by Chris2Brooks** [comment]
Hey @ferhatelmas 

Here's a sample post that's in the series that was originally posted as a blog post: https://swizec.com/blog/why-senior-engineers-get-nothing-done

There's a whole series of these articles in the newsletter curated based on their helpfulness as indicated by the readers of swizec.com

**Review by ferhatelmas — APPROVED** [review]
LGTM

**Comment by ferhatelmas** [comment]
@Chris2Brooks thanks.

**Pull request merged**
