### PR TITLE
Add Git Rev news

### PR DESCRIPTION
**Pull request by andyklimczak**
Great list, thanks! Not sure if a new group for git specifically is best. Just let me know!

### CODE REVIEW

**Comment by zudochkin** [comment]
Thank you for your contribution, @andyklimczak. It's OK for a separate section for git newsletter. Can you please put a full stop at the end of your last sentence?

**Comment by zudochkin** [comment]
And I will merge it.

**Comment by andyklimczak** [comment]
My bad, changed!

**Comment by andyklimczak** [comment]
travis failure might be a flake/outside of my control, just let me know!

**Comment by zudochkin** [comment]
Don't worry it's not your fault. I will fix those issues little later. Thank you one more time @andyklimczak 🏆 👍

**Pull request merged**
